### ISSUE TITLE
Create firefox and chrome extensions

### ISSUE THREAD

**Issue by mrspiderbrain** [ssbc/secure-scuttlebutt#106]
Being able to run scuttlebutt, and later scuttlebot, as firefox and chrome extensions will greatly expand the number of people who can free themselves from using corporate centralised databases for their social media needs. But how would we get there, and what individual things would need to be done?

**Comment by pfraze** [comment]
There are a couple of ways we can package https://github.com/ssbc/scuttlebot, which is the ssb node implementation that we'd want to use. Right now, we deliver it via npm and run it on the shell. The other options are:

 - Wrap it in Electron (formerly atom-shell, formerly node-webkit)
 - Put it in browser extensions

I believe both are good options. We'd want scuttlebot to run in the background, even if the browser is closed. If browser extensions can't do that, then I figure electron is the better choice.

**Comment by dominictarr** [comment]
people often leave tabs open long term, so not running in the back ground might not be a failure mode

**Comment by ahdinosaur** [comment]
+1 to using something like [electron](https://github.com/atom/electron) or [nw.js](https://github.com/nwjs/nw.js).

**Comment by albins** [comment]
As far as I know, there are Chrome extensions that (more or less) runs in the background. The Hangouts extension is one such example, but there may be others.

**Comment by dominictarr** [comment]
closing this, since we decided to go with electron app (which allows us to use crypto implemented in C, which is 20 times faster)
