### ISSUE TITLE
Remove 'secure' from title

### ISSUE THREAD

**Issue by jaimegem** [ssbc/secure-scuttlebutt#108]
Presenting the assumption of security by implying it in a database written in javascript(with no auth)'s name is abhorrent and, dare I say, snake oily.

**Comment by pfraze** [comment]
If you'd like to discuss the security design, and the history of the name, we'll be happy to do so. Otherwise, I'm going to close this issue.

**Comment by jaimegem** [comment]
::yells "mongodb!" as door slams shut::

**Comment by pfraze** [comment]
The "secure" refers to the feed's ability to validate its own integrity in the network, using signatures and a chain of content-hashes. This is not a database for storing secrets - in fact, the opposite, it's for publishing on a global network.

Authentication occurs (counter to your suggestion) via keypair crypto. As we're developing this alpha-status software, I won't claim perfect security or any nonsense like it. However I assure you there's nothing inherently insecure in this design.

I'm happy to discuss it more, but I do ask that you don't resort to ad-hominem.

**Comment by pfraze** [comment]
Going to close, but if anybody wants to continue discussing this, feel free and I can re-open

**Comment by dominictarr** [comment]
@jaimegem all writes to secure-scuttlebutt are cryptographically signed into a chain of messages (a "feed"). Messages cannot be removed or altered without invalidating the rest of the feed. There are other senses you could apply the term "secure", but I can assure this project has _very_ little in common with mongodb ;)
