### ISSUE TITLE
Key interoperation with SSH, GPG

### ISSUE THREAD

**Issue by pfraze** [ssbc/secure-scuttlebutt#111]
It would be really cool if the keys distributed over SSB could be used in either SSH or GPG. Do either of those support the key type SSB is using?

**Comment by dominictarr** [comment]
No I don't think so... we'd probably be asking for trouble.. I am thinking about changing the crypto libraries, but I think it would be much better to move forward to new algorithms rather than backwards to old ones

**Comment by pfraze** [comment]
FWIW gpg 2.1 adds ecc https://www.gnupg.org/faq/whats-new-in-2.1.html (behind a flag)

**Comment by dominictarr** [comment]
This is also affected by the chosen protocol attack:
https://github.com/substack/keyboot/issues/15

**Comment by dominictarr** [comment]
closing this
