### ISSUE TITLE
end-to-end messages

### ISSUE THREAD

**Issue by dominictarr** [ssbc/secure-scuttlebutt#114]
okay, time for end-to-end.

The obvious part:
we use `sodium.crypto_box(message, nonce, my_private_key, your_public_key)`
The nonce can be the hash of the previous message, that will ensure that it is not used twice.
That can then be base64 encoded.

questions: at what point is the message encrypted?
should it be like this:

``` js
{
  author,previous, seq...,
  content: <encrypted?>
  signature: ...
}
```
I took a long walk to think about this, and decided it was easiest if every message was like this, without nesting messages. I figure we need to do 1-1 encrypted messages, group messages, and encrypted attachments... in the long run, we should start with 1-1 but need a game plan for the others.

as I mention above, 1-1 is easy, but how would group messages or blobs work?
in a group message, you need to tell someone the key (delegate them the access cap) and to do that you post them a special 1-1 message delegating them the cap.

An encrypted attachment has a different challenge. you need other parties to know about the attachment, so they can help distribute it, but not to access it. to do this, you post a simple message that links to the encrypted attachment, via an ordanary `{ext: ciphertext_hash}` link but does not provide the key. Then, in a group or 1-1 message, you provide a link that has the key! `{ext: ciphertext_hash, key: key, name: filename}` but normally that should be nested inside a private message
(although, you COULD post it plain if you wanted to distribute a private file, and then release it later)

**Comment by dominictarr** [comment]
An encrypted message would just be a sealed box with no lable on the outside (there should be no TO field) to find out whether it was for you, you try and decrypt it, and if it authenticates then it was, else no.
For every encrypted message you see, you try and decrypt it as if it was addressed to you, and then the groups that you are a part of.

This might be a little expensive `O(g)` if you are in `g` groups, but probably okay - way more private that way though, alternatively, you could use the hash of the secret as the group id, and then you can tell whether you are in that group or not. but you can also tell who is in a group. I think it's better to keep it private.

**Comment by ahdinosaur** [comment]
> An encrypted message would just be a sealed box with no lable on the outside (there should be no TO field) to find out whether it was for you, you try and decrypt it, and if it authenticates then it was, else no.
For every encrypted message you see, you try and decrypt it as if it was addressed to you, and then the groups that you are a part of.

i like this approach to encrypted messaging, so simple.

**Comment by pfraze** [comment]
This looks good. I agree that it's the right kind of simple. For multiple recipients that dont have a set of keys pre-negotiated, how will it work? Will the message be sent encrypted symmetrically, and then have 1 extra message for each recipient that includes a copy of the key? Or will the message be sent once for each recipient?

**Comment by dominictarr** [comment]
ah, I hadn't thought about that. to be honest, emails to multiple people are quite annoying...
with what i was thinking you have to create an explicit group, and then send messages to that group.
If you create many short term groups, yand peers needed to try every key in every lock then it would get more and more expensive.

Okay, hmm, one compromise would be to give the groups an "id" when you post a message to a group, you'd `hmac(my_pub, group_key)` and now if you knew `group_key` (i.e. you are a member of that group), then you can test whether I am posting to your group, without revealing group membership... Although, it would reveal that a given peer has posted N messages to a private group.

hmm, there are quite a few tradeoffs to group messages, we should leave that on the drawing board for now...

**Comment by dominictarr** [comment]
hmm, a much simpler group model might be if you add people to a group, but it's only a read cap.
So I could have a "private wall" and id add you to it, but you'd have to add me to your own wall.
This way, if Alice posts an encrypted message, Bob would attempt to decrypt it with mult(A, B) and with any group keys Alice has given him... hmm, that is gonna scale much better, and will still work pretty well for a p2p social network.

**Comment by dominictarr** [comment]
to remove someone, you need to update the key for everyone.
you could generate a random sharing key Pk, plus the hash of the secret hash(s)
``` js
Kp, hash(s)
adds=friends.map(F: box[Ks*Fp](s))
```
then, to decrypt, combine Kp with your secret (Ms)
```
s  = adds.find(A: unbox[Kp*Ms](A)===hash(s))
```
you could leave the mac off each box, since you have hash(s),
and then it would be 32 bytes per friend + 32 bytes for Kp and 32 bytes for hash(s)
which means you can update the key for 30 friends in just 1 k.

**Comment by dominictarr** [comment]
or, if you removed the hash(s) and instead used a mac on every secret, then you could also encrypt a secret to the person you are removing (except, give them the _wrong_ secret) making it not immediately obvious they are kicked... hmm, would be obvious enough when they realize they can't read as many messages as they could before.

**Comment by pfraze** [comment]
In these schemes, there's a local set of keys which the user has to try against messages. 
(1 for each group the user is a member of.)
Larger sets will degrade performance, so there's going to be a limit to how big the keyset can get.
Depending on how low that limit is, we may run into issues managing the keyset.
For instance, we may have to pre-arrange groups, meaning messages can't have an ad-hoc set of recipients.

An alternative is to explicitly provide `recp` keys on the message headers. *Unfortunately, this won't work out, see below.*

- Add a `recp` header to the messages.
- If the msg is plaintext, `recp` would be null.
- If the msg is encrypted, `recp` would be an array, containing the symmetric key of the `content` ciphertext, encrypted using the longterm pubkey of each recipient.

Reading users would try to decrypt each entry in the `recp` array using their longterm seckey.
If the output is valid (possibly by checking a tag on the string) then they would decrypt `content` using it.

The benefit of this is, you're only attempting to decrypt `recp` entries with the longterm seckey, so recipient-detection is `O(n)` where `n` is the number of recipients.

*This won't work, unfortunately.*
The downside is, each message would reveal the number of recipients.
This could reveal that a message is a reply to another message.
For instance, if a message has 5 recipients, and then 4 other people start sending messages with 5 recipients... it's a good chance that's all part of a thread.
And worse, we now know who those 5 people are ...so the recipients are deanonymized.

Most of the time, this wouldn't be possible.
1 recipient would be very common, for instance.
But the chance of a leak isn't acceptable; it makes the tool too hard to reason about.

We'd need to tweak this approach somehow.
Possibly as a scheme to arrange ephemeral group keys (eg each thread has a key)?
That's only useful if it helps us control the local keyset's growth.

**Comment by dominictarr** [comment]
this is now implemented: https://github.com/ssbc/secure-scuttlebutt/pull/116
