### ISSUE TITLE
idea: detach message content from message

### ISSUE THREAD

**Issue by dominictarr** [ssbc/secure-scuttlebutt#124]
If we split the message into two parts several good things could happen.

but first: i mean header: `{previous, author, sequence, timestamp, content_hash, signature}` and then `content` as a separate small blob. the headers would form the chains, and the messages wolud hang off the sides.
1. it would be easy to "delete" messages, forget the content, but keep the header, this would allow peers to maintain safe harbour protection, avoiding copyright liability if someone in there network posted a copyrighted work. Also, useful for policing abuse, or worst of all, when you misspell something and then hit send and everyone realizes you are an intellectual fraud.
2. it would be easy to create a proof that a given feed is compromised: post a message with two messages from that feed with the same sequence and valid signatures. it would not need to include the content of those messages.
3. since the headers are now a fixed size, it would work really nice in a binary encoding.

**Comment by pfraze** [comment]
These are strong positives, especially 1. Also, in JSON, the headers are around 300 bytes. They'll be smaller in binary.

My first reaction was, "we'd have to roundtrip request each message, individually, by hash!" But actually, we wouldn't -- we just send the `content` automatically with the headers stream. (In fact we could do that with blobs too if we wanted... hm.)

**Comment by pfraze** [comment]
1 is also good for garbage collection

**Comment by ahdinosaur** [comment]
:+1: this makes a lot of sense.

**Comment by pfraze** [comment]
Would doing something like this also let us drop the content-size limit, you think?

**Comment by dominictarr** [comment]
yeah, we should send the content automatically, but in that case we need to keep the content limit.
i don't think we should send the blobs automatically, not in general at least. since multiple people can post a link, they may already that blob. also, blobs can be large etc.

**Comment by dominictarr** [comment]
okay with a binary header the size will be:
`32+32+8+8+32+64 = 176` bytes. it does improve the overhead, but i don't really feel it's as strong an argument as 1) which give the peer another freedom.

**Comment by pfraze** [comment]
Good point about blobs.

How do you plan to do hash and key algorithm tags in binary?

**Comment by dominictarr** [comment]
ah, good question... maybe add two more bytes?

**Comment by dominictarr** [comment]
Although, i'm kinda leaning towards just leaving that out... algorithm agility just makes it way harder.
maybe better to use the best crypto available to day, and when the time comes, hopefully someone has figured out a better system, anyway?

on the other hand, we could stick a few more bytes in and we might be thanking ourselves later.

**Comment by pfraze** [comment]
Yeah, Im inclined just to stick in the extra bytes. We might also put an ssb version in the headers?

**Comment by ahdinosaur** [comment]
where ssb version == hash of message schema :smile:

**Comment by dominictarr** [comment]
@ahdinosaur but then we need to invent a schema description system!
