### ISSUE TITLE
Delete method

### ISSUE THREAD

**Issue by pfrazee** [ssbc/secure-scuttlebutt#128]
Unbounded growth is a common concern that I hear about from people, when I tell them about SSB.

I suggest we add a delete method with the following advice:
- Unless the user is abandoning the log, never delete entries that are in logs by the local user.
- Only delete entries which you're certain have been processed, and won't need to be referenced in its original form. If you're not sure, keep the message - it's not that big.
- Though there are no guarantees, you can usually refetch messages from the mesh.

Here's the changes I'd suggest:
- Add a delete method, which can accept a message-id, array of message-ids, or feed-id. It should batch-remove the messages and their index entries.
- In scuttlebot, add tools to redownload messages which were previously deleted.

**Comment by dominictarr** [comment]
having deletes without rewriting feeds to use a merkle tree would add _a lot_ of complexity. deleting whole feeds or deleting blobs would be fine though. reasoning about which things can be safely deleted would be very difficult.
