### ISSUE TITLE
Easier way to get the receive time of a message?

### ISSUE THREAD

**Issue by pfrazee** [ssbc/secure-scuttlebutt#133]
It's pretty hard to get the received timestamp of messages, right now. The only way I know of, is to fetch the message from the logdb stream, in which case the receive-time is the key.

Is there another way? Ideally, the receive time would be in the output of all of ssb's functions. Second-best would be having a function to get the receive time for a given key.

**Comment by dominictarr** [comment]
not currently. i have been considering having a reverse index of msg id -> received ts, but I think we should try feeds based on filtering the log db. basically it would work by iterating forwards and backwards through the log stream, and filtering out messages with particular properties (i.e. posts). That would give us received order and it could also be easily applied to filtered feeds of other things.

**Comment by pfraze** [comment]
So you're thinking about removing the non-log indexes?

**Comment by dominictarr** [comment]
I want to see if we can come up with something that feels like it can provide good UX for you and feels simple and databasey for me.  Especially with a view to being scalable for filtered feeds (for new apps based around a particular message type, or filtered into a category, etc)

**Comment by dominictarr** [comment]
this is now attached to each message
