### ISSUE TITLE
Why do messages include the feed's public key?

### ISSUE THREAD

**Issue by paulkernfeld** [ssbc/secure-scuttlebutt#138]
Wouldn't it be enough to only have the public key in the first message?

**Comment by pfraze** [comment]
That's a good question. The pubkeys are not too big, and doing so makes authorship identifiable if you find a message by itself (eg in a log).

**Comment by paulkernfeld** [comment]
Is there any way that the pubkeys could be removed from messages, at least when persisted in the DB and when sent over the network? I think this would optimize storage and network performance by a maximum of... 20%?

**Comment by pfraze** [comment]
Yes, at the cost of a little complexity. @dominictarr what do you think?

**Comment by dominictarr** [comment]
I don't think this would be worth it. you could just pipe the raw plaintext through a standard compression and it would remove most of that, but writing a manual thing would add quite a bit of complexity.

**Comment by paulkernfeld** [comment]
Yup, makes sense. Thanks for your patient explanations guys!

**Comment by pfraze** [comment]
Sure thing, they're good questions
