### ISSUE TITLE
Why do messages need a sequence number?

### ISSUE THREAD

**Issue by paulkernfeld** [ssbc/secure-scuttlebutt#139]
The sequence number is used to make sure that a malicious node can't give us a feed with reordered or omitted messages, but can't we verify that just by looking at the prev hash? Does the sequence number have another purpose that I'm missing?

**Comment by pfraze** [comment]
Same logic as with having the public keys on the messages, I think

**Comment by paulkernfeld** [comment]
Now that I'm thinking about it, this might be a pretty important optimization for long feeds, since otherwise I think you'd have to traverse the entire feed in order to count how many messages you have.
