### ISSUE TITLE
Why are feeds identified by the hash of the public key?

### ISSUE THREAD

**Issue by paulkernfeld** [ssbc/secure-scuttlebutt#140]
Since public keys are only 32 bytes (256 bits), why can't feeds be identified by the pubkey itself?

**Comment by pfraze** [comment]
That's not the case anymore. We used to use a key-type that was much longer, so we needed the hashes. Then we moved to the present keys, which are 256 bits, and stopped using the hash. 

Did you see something in the docs saying that? If so that needs updating.

**Comment by paulkernfeld** [comment]
Oh, okay, that's actually great! The README was a little stale. I updated it here: https://github.com/paulkernfeld/secure-scuttlebutt/commit/a7a57e322dad84b8cfaeb91ffe6807ed65a7fa85
