### ISSUE TITLE
improved link indexes

### ISSUE THREAD

**Issue by dominictarr** [ssbc/secure-scuttlebutt#142]
Often, we have named links, for example an ordinary hyperlink has an href and text that is clickable.
in patchwork, when a username is mentioned, it becomes a link to their feed (public key)
But, since we didn't index the extra data associated with the link it's hard to get the names that have been linked to someone back out.

In my [naming plugin pr](https://github.com/ssbc/patchwork/pull/251) I had to scan all the mentions (ever!) to find who had been named a given name.

I propose to change how link indexes work, to make "rel" a path. so a mentions link would look like
`[source, ['mentions', name], dest, msg, ts]`

and the reverse index:
`[dest, ['mentions', name], source, msg, ts]` (this will make it very fast to see what someone has been named, without retriving the actual message they where named in - query for `[dest, ['mentions', *], *]`
just that I know `["mentions",..]` will be enough to skip the other rels for dest, making this index efficient.

And expand a third index which is rel first.
`['mentions', name], dest, source, msg, ts]` then I can easily see who has been named "bob", by anyone.

I know that full graph databases often have 6 indexes (SRD, SDR, DRS, DSR, RDS, RSD) but I think it's good that we only add them as we actually need them.

This also leads to a discussion of link formats, I don't want to make everyone start again, so the message types that patchwork uses should be handled in the current format (this will require handling some special cases)... but that should be another discussion.

**Comment by pfraze** [comment]
Is `name` an attribute in the link? If so, it would just be undefined if not present?

**Comment by dominictarr** [comment]
I think we should handle the current rel types (about, mentions) as special cases that have name inserted, but once we are happy with that, we should think about redesigning how links work.

**Comment by pfraze** [comment]
Why make this core vs implementing it as a materialized view in `ssb-names` ?

**Comment by dominictarr** [comment]
Hmm, okay maybe we should discuss what would be a better link format now.
ssb-names has shown us what it secure-scuttlebutt needs to be to be useful. the point of indexes is to make things easily retrivable. naming things is very generic, you could also apply this pattern to tags and so on. we have a type (the rel - mention) and a value (the name - "paul") and probably others. you can currently query votes, but not +1 votes only...

This would give us a new power, and that is a lot better if we can do it than putting pretty much the same materialized views in everything.

**Comment by pfraze** [comment]
I'm not totally clear what you can't do now, that this would remedy. Would this be solved if `type: about` put the name inside the link object?

**Comment by pfraze** [comment]
Or, is there more to it?

**Comment by dominictarr** [comment]
no, that wouldn't solve it, the name needs to go into the index

**Comment by dominictarr** [comment]
I want to get all the feeds with a name that matches something - so I know the rel, the name, but not the source or the dest.
so I need an index that goes `rel, name, source, dest`

**Comment by pfraze** [comment]
so "give me all links where rel=mention and name=pfraze"

**Comment by dominictarr** [comment]
also, note that links aways have a namelike thing about them `[name](dest)`

**Comment by dominictarr** [comment]
yeah, basically... we could do a sql thing here, but that is way more compex. if the rel is a path that a small change to what we already have, but still very useful I think.

**Comment by dominictarr** [comment]
also, note that you can have a link inside a link `[![alt](img)](dest)` but if you go deeper it doesn't make sense because the inner thing is not clickable.

**Comment by pfraze** [comment]
Yeah I'm just not convinced that this is that generic. What would be the path from special-casing it to a general behavior?

**Comment by dominictarr** [comment]
we'd make a new link format that was closer to the index format, but still interpret the legacy links as valid for those cases. in the interim you could make posts that are valid both in old and new form.

**Comment by pfraze** [comment]
what might the new link format look like?

**Comment by dominictarr** [comment]
upgrading something like this is also something we need practice at.
I'm thinking it could be a markdown link `[name](dest)`, or something like that.
one layer of nesting is allowed, so you can have `[[name](dest1)](dest2)` to relate two things.
and maybe some official separator `[vote:+1](dest)`

**Comment by pfraze** [comment]
(I have no problem running an upgrade)

So, like

```js
{
  type: 'vote',
  vote: '[vote:+1](%asdf...sha256)'
}
```

?

**Comment by dominictarr** [comment]
yeah. and in that case the `"vote":` property is no longer considered the rel, that is now inside the link.

**Comment by dominictarr** [comment]
also, this means we can say things like

`[owner: @paul](@paul's cat)`

**Comment by dominictarr** [comment]
and generally make subjective claims about such things.

**Comment by dominictarr** [comment]
hmm, your cat probably doesn't really think of you as it's "owner". so maybe it should be `[feeder:@paul](@pauls-cat)` then if I meet your cat out somewhere, I can scan it's QR code badge and query who feeds it.

hmm, maybe that should be `[[feeder](@paul)](@cat)`?

**Comment by pfraze** [comment]
Would a new syntax be necessary? We could just standardize new attributes on the link object, and avoid writing parsers.

Im also not convinced this is something we should solve in core, at least not yet. You say we'd end up putting the same materialized views in every app, but I'm not convinced that's the case, and if it is that's solvable by other means (like having apps communicate with each other). What I dislike about adding to core is that it adds complexity in an ad-hoc way. It's a lot harder to take something out than to add it.

**Comment by dominictarr** [comment]
the worst thing would be to solve what are essentially the same things in different ways in different apps. That would really be adding complexity. Solving in a flexible reusable way would be worth putting in core.

Unfortunately we havn't used links very consistently, so mentions have the names in the link, but about messages put the names beside the link. _that_ adds complexity, because I have to handle both those cases specially in ssb-names although they are both doing the same thing: naming.

**Comment by dominictarr** [comment]
I'd be okay with standardizing the link properties, but this isn't really a new thing, it's markdown,
and if we have max 1 nested link then that is parsable via a regular expression.

**Comment by dominictarr** [comment]
so it would be cheap, and also, it's valid markdown, so we arn't really inventing a new thing.

**Comment by dominictarr** [comment]
Also, avatars are another example, it's just like a name, except it's a picture of that thing.

**Comment by dominictarr** [comment]
@pfraze if you want to argue that this isn't generic enough, you need to show reasonable cases that wouldn't fit.

**Comment by pfraze** [comment]
There's nothing that wouldn't *fit*, in the sense that it would be broken by this change, but there are plenty of things that would have no use for this change, and that's why I question whether it's generic enough. 

It feels like... let's say we were creating a SQL engine. It currently selects by ID, and indexes by foreign-key relations, and now we're talking about adding an auto index on the name column, if it exists. Well, ok, that's sort of useful, but also kind of random. What's the endgame? Is this a temporary feature, on the roadmap to adding application-set indexes? Or is this going to be something that happens to be there, while most serious work is done by materialized views?

I'm not trying to jam you up here, but we've historically been slow to change core, and I think that's a good thing. This idea doesnt strike me as opening up a lot of new options, or saving us from writing a lot of materialized views. And if it involves a syntax change, it's a protocol change, which makes it a pretty big task, so that's an even higher bar. And I'm generally not a fan of syntaxes anyway.

**Comment by dominictarr** [comment]
we arn't building an SQL database, we are building a graph database... that is socially edited.

materialized views are popular this season, because of nosql... but, that is characterized by "web scale" startups that have massive datasets and they need every query to respond within a fixed window (else users get bored and leave) we also need to respond within in a fixed window, but, our dataset is _small_. Or rather, we have many small datasets. Because of this, some degree of querying and scanning and filtering is fine, since each node only has to service about 1 user, it's quite okay to do a little work, the response time only has to be fast enough to _feel fast_.

On the other hand, having a materialized view for every query you need is quite expensive. That would make every feature expand the size of the database by some factor.

This is a pretty weird database. anyone can edit it, but they can only edit one little sliver. If they want to affect something over there, they have to _link to it_. That is pretty much all we have to work with, that is why we have indexes on the links in core... we have links, and links with data, we already have indexes to query those links, I'm just saying we need ways to query the data about the links too.

**Comment by dominictarr** [comment]
looking at the actual materialized views you are using, you see things like https://github.com/ssbc/patchwork/blob/master/api/processor.js#L125-L137

you want to know which users are flagged by whom? and who flagged this user? Those are link queries. You are just using materialized views to build _your own_ link indexes. That shows that you need link indexes, so lets fix the indexes we have.

**Comment by pfraze** [comment]
The SQL engine example was an analogy to explain why this feels half-baked to me.

We dont use materialized views because they're a flavor of the month. We use them because ssb is a log structure, and it's not performant to do full log scans at query-time, and we chose not to fill core with a standard set of views. So, we have applications producing the views. Your proposal doesn't change that; it just adds features to one that's already in core.

The root of what you're suggesting is to improve the link index, in order to reduce the frequency of redundant indexes made in applications. I don't have a problem with that idea, but I'm not yet convinced by this solution.

It might be interesting if we indexed every KV in the link object. That would be more general. Eg:

```js
{
  type: 'vote',
  vote: { link: 'asdf', value: -1, reason: 'abuse' }
}
```

creates two entries in one of the index directions:

```
[source, ['mentions', 'value', -1], dest, msg, ts]
[source, ['mentions', 'reason', 'abuse'], dest, msg, ts]
```

But I still think we should have an idea of the endgame before making that change. If the thing we're trying to solve is redundant materialized views in application space, I think this is only a partial solution. We'll still need other views. Would we continue to move them into core, as we define them? Or, is the solution to put materialized views in sbot plugins, so that users can define new views and then share them with other applications? Or, should we create language for describing materialized views which core can then implement, like SQL does for table definitions? (Probably not that last one, but I'm just including it for completeness.)

I'm not against this idea at all, but I want to address it holistically.

**Comment by dominictarr** [comment]
Yes, we could do that, but it would be far more complex than constraining links so that extra data became a path (strictly left-to-right) rather than key value. key value is hard to index because you what happens when someone posts a link `{value: +1, reason: 'abuse'}`? now you need a dual index...
So what I'm saying is that kv is _too flexible_, we should constrain links so that the data is ordered from most to least significant because it will make indexes way simpler.

If the message designer needs more than one piece of metadata about a link they need to decide how they are gonna get it out. It's easy for them to decide which thing they need to query, but hard for the database to do that. so you could easily pull out the votes by +1/-1 by putting that first.

Materialized views are efficient to read, but not necessarily to write. There aren't any database techniques which are general purpose. We need to have a range of tools that solve a range of problems.
I'm not against materialized views in principle, but I'm against using them when they are not really necessary.

**Comment by pfraze** [comment]
> I'm not against materialized views in principle, but I'm against using them when they are not really necessary.

I think this is where we differ. I'm not against alternatives to app-defined materialized views, but I'm against adding them case-by-case. Any feature we add to core complicates sbot and the protocol, so it really needs to be worth it. App-defined views meanwhile are extremely general and conceptually simple, and don't complicate core's concepts at all. They're tedious to define, but that can be improved with third-party libraries.

The biggest cost to app-defined views is the chance of disk-bloat from redundant definitions. I don't really see that being a problem in the near-term, and I think that's something that userland could solve eventually if applications have RPC.

**Comment by dominictarr** [comment]
my job here is to look for patterns and then reduce them down and implement the fundamentiall aspects of them... it's decomplexifying. But I see I'm not gonna persuade you like this so I'll implement this as a plugin...
