### ISSUE TITLE
Easily replicating between two scuttlebutts?

### ISSUE THREAD

**Issue by paulkernfeld** [ssbc/secure-scuttlebutt#148]
I'm interested in using secure-scuttlebutt as part of a P2P project I'm working on. One thing that I'd like to be able to do is to easily pipe two scuttlebutts together to make them replicate with each other, maybe like how [hypercore](https://github.com/mafintosh/hypercore) does it. That way, I can connect them using something like [discovery-swarm](https://github.com/mafintosh/discovery-swarm) or [webrtc-swarm](https://github.com/mafintosh/webrtc-swarm). Is there currently code that makes it easy to do this? I see that there's a [replicate.js](https://github.com/ssbc/scuttlebot/blob/47806d0910e08733427dcd83c69ac25b1c8095ac/plugins/replicate.js) file in the scuttlebot project, but I'm interested in something more general. I'm guessing that I might need to write a new library to do this, which is fine with me.

**Comment by dominictarr** [comment]
You could pull this off with just a bit of glue code. normally, replication is automatic, and is trigged when sbot realizes it's connected to another peer.

What is your goal here?
I'd love to have support for utp in standard ssb, I couldn't install webrtc on node though.

it would be best if we made pubs act like the "signal hub", and then that is also more decentralized than using a specific server to introduce your peers.

**Comment by paulkernfeld** [comment]
Well, I was hoping to use secure-scuttlebutt without sbot, since I want to use a different network layer. Specifically, I would like to be able to replicate feeds without any invites taking place. Also, the ssb replication logic seems to contain some math governing how much of the feed to replicate, and I'd like to replace that with my own logic.

That said, I think I might end up using hypercore instead of secure-scuttlebutt, since it seems to be better suited to my use case.

Yeah... webrtc is a pain. I assume you've seen [electron-webrtc](https://github.com/mappum/electron-webrtc)? Maybe that would be a useful building block.

**Comment by dominictarr** [comment]
ah, right. it would depend on what sort of application you are building. it is relatively simple to disable particular parts of scuttlebot, since most of those features - replication patterns, etc, are controlled by plugins.

what sort of application are you building?

**Comment by dominictarr** [comment]
Oh, I didn't see `electron-webrtc`, I just saw `wrtc`, which failed to build.
