### ISSUE TITLE
proposal: rename `secure-scuttlebutt` repo / pkg to `ssb-db`

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/secure-scuttlebutt#159]
see discussion on ssb [here](https://viewer.scuttlebot.io/%25BIn4rQl8o7PxeolhiZCw77fUN5gGpOv6I3gDXhMfP%2BM%3D.sha256).

**Comment by staltz** [comment]
The viewer link isn't working for me, but I'm 👍 for this idea.

**Comment by dominictarr** [comment]
I'm okay with this, I'm intending to rewrite using depject, so this can be the name for that.

**Comment by clehner** [comment]
> The viewer link isn't working for me

should be fixed now

**Comment by christianbundy** [comment]
- [ ] Remove internal name references (#242)
- [ ] Rename GitHub repo
- [ ] `npm publish` as ssb-db
- [ ] [`npm deprecate`](https://docs.npmjs.com/cli/deprecate) secure-scuttlebutt
