### ISSUE TITLE
Documentation: mail servers

### ISSUE THREAD

**Issue by mitar** [ssbc/secure-scuttlebutt#160]
In "Design Challenge: Avoid Centralization and Singletons" section it is written:

> Contrast this with email servers, which are ostensibly decentralized (you may run your own email server) but you must have exactly one email server, and if it is down you will not receive email, which makes running your own email server a considerable hassle (not to mention handling spam).

That is not really true. You can have multiple e-mail servers and multiple MX records for your domain name pointing to them. You can have so that any of them accept your e-mail and then distribute it to others if and when they are online.

**Comment by dominictarr** [comment]
interesting - so you still have to own the domain, but you can run a cluster of mail servers?
it seems some of our complaints about email servers are still valid, but what we said could be more accurate. the domain is still a point of failure, this is a good illustration of how https://medium.com/@N/how-i-lost-my-50-000-twitter-username-24eb09e026dd#.s2849vjpf

**Comment by mitar** [comment]
Yes, you can run a cluster of mail servers. This is pretty common. You can even [specify priorities](https://en.wikipedia.org/wiki/MX_record). 

> it seems some of our complaints about email servers are still valid, but what we said could be more accurate

I do not think any of your statements in the quote above is true. I mean, I can always decide to accept only PGP signed e-mails from people I know their public keys of, and then I do not have spam issues. (This is what secure-scuttlebutt and e-mails analogy would be for me.) I can run a cluster of them. And I can use DNSSEC to make sure my e-mail domain is hard to change by some non-trusting party.

I do not know, I think the example is a bad one. It is one of the mot decentralized protocols we still have in active use this days and I think it is not reasonable to make such claims. It is true that in practice most people use a centralized service like Gmail, but those are different forces.

**Comment by dominictarr** [comment]
okay, well if you really want to preserve the honor of email, please make a pull request with more accurate documentation and we'll merge it. describing the sort of email setup that would be analogous is good.

**Comment by mitar** [comment]
:-)

Do we have any other bad example we would like to use instead? :-) Some centralized chat? Facebook?

**Comment by ahdinosaur** [comment]
Facebook, Twitter, GitHub, and [even Signal](https://whispersystems.org/blog/the-ecosystem-is-moving/) are good examples of centralization. dns, Bitcoin, BitTorrent, Ethereum, Twisted, etc (so many) are all good examples of singletons.

- [%lmELhGVLXcWrygyG0whgkzkmjlmiB1jZf5EshQ5zfhs=.sha256](https://viewer.scuttlebot.io/%25lmELhGVLXcWrygyG0whgkzkmjlmiB1jZf5EshQ5zfhs%3D.sha256)
- [%0asWjhFa51ri/OOSXJgC/aUweNzhxHi2/7+PXhwUzH8=.sha256](https://viewer.scuttlebot.io/%250asWjhFa51ri%2FOOSXJgC%2FaUweNzhxHi2%2F7%2BPXhwUzH8%3D.sha256)

more at <https://www.scuttlebutt.nz/concepts/>. if you want to help @mitar that'd be great. :cat:

**Comment by mitar** [comment]
Done: https://github.com/ssbc/docs/pull/21

But I didn't really know what to write about email there because it does not really correspond to that section anymore (if we agree that it is not as centralized as it was before written). I think we should probably just remove that paragraph and this is it.
