### ISSUE TITLE
Documentation: receiving messages from unknown people

### ISSUE THREAD

**Issue by mitar** [ssbc/secure-scuttlebutt#162]
I am reading this:

https://ssbc.github.io/docs/articles/design-challenge-sybil-attack.html

What is the story to allow people to receive messages from unknown people? Without that it is really hard to claim that unsolicited spam is a problem of e-mail. I mean, I could always allow only receiving e-mails from people in my address book? (OK, somebody could still fake the address in From, because that is not signed in e-mails, but it would still minimize spam to a very small number.) Something similar is done in [greylisting](https://en.wikipedia.org/wiki/Greylisting).

So to me it seems that ssb is not providing a solution to this problem, but just provides a different set of defaults, with the feature of unsolicited messages disabled. Maybe that is a better default, but it is not solving the fundamental problem.

Also, it is an interesting that this is in the chapter titled Sybil Attacks. Because how it reads is: "Sybil Attacks is when you have an open network anyone can join and send spam messages. We solve this by preventing anyone sending messages without you first allowing them to send messages to you." But then this is not an open network anymore, in a sense. It is federation of closed networks (per feed), or permissioned networks.

In  blockchain world you have permissionless and permissioned blockchains. Permissionless have to use things like proof of work. But permissioned use (centralized) authentication to know who is writing to a blockchain and this can change design a lot and allows things use of protocols like practical BFT.

In the case of ssb it looks more like a federation of permissioned blockchains (hashchains) where each blockchain can be appended only by one user. Then you do not really have Sybil Attacks, because you have closed networks.

BTW, how does one learn about feeds of others? Could you have spam there? Spamming with sending "friend requests"?

**Comment by dominictarr** [comment]
currently, we havn't implemented unsolicited messages, but it could be done like invite codes are - you'd give out cryptographic tokens, which allow you to contact a server, and then the server posts a message to it's feed on their behalf that you can read. you could also have another arangement where mutual friends relay a message for you.

you learn about new feeds through your friends. my friend posts a message saying that they follow someone, and I see that, and can choose to follow them (or not) also. Currently the default is to replicate your friends + their friends. This provides availability to the network. some clients like [patchwork](https://github.com/ssbc/patchwork) do not show friend-of-a-friend in the main feed, other do, but if you have their message you can see their replies.
