### ISSUE TITLE
Signing states of each other feeds to build a global consensus

### ISSUE THREAD

**Issue by mitar** [ssbc/secure-scuttlebutt#166]
I love SSB but I like one feature of Matrix which is that it confirms feeds of each other so that you get some collective protection against roll back attacks. I think SSB could integrate something similar very easily. Imagine that I see a feed A at message X, then I could sign a message on my feed B saying that I saw feed A at message X. If a peer is following both A and B, then if message X does not appear in A, the can know that something potential bad is happening there.

So in some way you merge heads of all feeds across each other. And gives a form of global (for a subnetwork of users) consensus which has both persistence and liveness, two main properties of a blockchain. (It does not prevent double spending though.)

Maybe liking and replying already do that in a way. But it would be interesting to do some computing of consensus across you and your peers and surface that. By computing that you might deter attackers because they would know that they will be detected.

**Comment by dominictarr** [comment]
yes, I've definitely pondered this. It could be very useful to detect when a key has been compromised, and let you see which messages are authentic, although you couldn't append any more messages.

**Comment by mitar** [comment]
Hm, detecting compromised keys is something else, or at least not what I had in mind opening this issue. Based on my understanding of both SSB and Matrix I think the issue in SSB is that you do not really know if you got the whole feed. You have to:
* trust that gossip worked and you got a message in real-time
* trust that pub is giving you all data

Now, if you would have signed messages in various feeds on what other state of feeds they have seen, the attacker could not selectively deny updates to only one feed, but would through time had to deny updates for all feeds, because you would discover from other feeds that there is something new in feeds you have thought you have the latest information.

**Comment by dominictarr** [comment]
Oh right, matrix has this problem worse that ssb, because although one pub could pretend that you didn't post a message, you could just hear about it from someone else. _all_ the servers would need to collude to not give you my recent messages.

let me explain what I meant about key compromise though - suppose someone compromises your key, and then posts a message that looks old, with a low sequence, and then gives new people this instead of your old messages. This would be detectable because no one would have replied to those messages, but they would have replied to your original messages.

**Comment by mitar** [comment]
True. That could also work for compromised keys now, agreed.

**Comment by ahdinosaur** [comment]
related: [%hoeiiStgKp4/Z54Lp2fuMYQ/Guepbfk/Ml3YV77Y0XU=.sha256](https://viewer.scuttlebot.io/%25Rm0owi%2FjsuuQLq0jDK7unxijRwakCvo4bA4%2F9bgVE5w%3D.sha256#%25hoeiiStgKp4%2FZ54Lp2fuMYQ%2FGuepbfk%2FMl3YV77Y0XU%3D.sha256)
