### ISSUE TITLE
Vision of SSBC on the future of Decentralized Computing?

### ISSUE THREAD

**Issue by aschrijver** [ssbc/secure-scuttlebutt#180]
Hi,

I recently gained an interest in decentralized computing and found it a greenfield IT area with very little contenders and unique challenges.

So I started a (long, because of me) discussion thread on the Dat Project on where the field is headed, and what are the vision and strategies of its players.

I guess much of what I bring to the table applies equally well to ssbc. Therefore I would invite you to have a peek at the discussion, see if there is anything there for you!

https://github.com/datproject/dat/issues/824#issuecomment-315973933

**Comment by dominictarr** [comment]
ah, thanks. that thead is _very long_ could you give an executive summary?
btw, I wouldn't consider ssb and dat to be "competitors"

**Comment by dominictarr** [comment]
in the sense that one doesn't have to fail for the other to succeed, indeed they do play with similar ideas but they also have different approaches! There are lots of ideas moving back and forth between each.

**Comment by aschrijver** [comment]
I agree @dominictarr , and I'll gladly provide an executive summary :+1: 

**Executive summary**

* Decentralized computing holds the promise of The Decentralized Web
* The field is still largely empty, undiscovered 
* There are only a handful of players
* This puts these early-bird players in a very special position
* Usually where such Google-sized niches exist every party would jump on the bandwagon
* But there exist unique forces working against the success of DC: government and commercial powers
* Looking at history most of preceding DC initiatives have failed.. but not due to evil powers
* They failed mostly due to unrealistic vision, combined with bad organization / community building

--> They failed because did not properly define _the roadmap to their own success_ (maybe some even didn't define success at all)

As a newcomer (interested in building a social network) I made following observations on some currently viable candidate technologies (i.e. the players, and specifically IPFS, SSB, Dat and Replikativ):

- All candidates, except maybe IPFS, are still very fragile, in their infancy
- IMO they incorporate many of same mistakes of their failed predecessors
- Only _real_ standardization efforts are IPFS and Dat. Of these IPFS is the most likely to succeed
- But both IPFS and Dat target just a small DC sub-domain: file sharing
- This makes IPFS unsuitable to me, but current Dat design allows it to be easily repositioned
- Expanding vision and positioning as a message-based system would be high value, low impact
- Same holds for SSB: lose application focus, broaden horizon, define your success

Now, where previous failures had mostly themselves to blame, you are of the first generation of DC software initiatives that _will_ be challenged by the dark powers
And this time the stakes are much higher! Very comparable to climate change. Action is required _now_ to avoid future disaster. Instead of climate its about the internet

Slightly exaggerated, but in essence true, the choice is for  a future internet where there is:
- either freedom of expression and people control their own data and privacy
- or controlled thought in a 1984 + cyberpunk (without the magic) type of society
 
**Recommendations**

- Analyse and understand your unique position
- Then be conscious of the moral responsibility that comes with it
- And what that means to how you approach the 'market'
- Foster grass-roots and open-minded culture, cooperation
- But be much more strategic in your approach
- Define the recipe to your success with all this in mind
- And reorganize accordingly, so you come prepared

**Quick reference**

- [Traction, exposure, moral responsibility](https://github.com/datproject/dat/issues/824#issuecomment-315740501) (+ case study for good organization)
- [Dat repositioning, expanding vision and benefits](https://github.com/datproject/dat/issues/824#issuecomment-315522942) (+ reorganization brainstorm)
- [Dat repositioning as a message-based system, the technical aspect](https://github.com/datproject/dat/issues/824#issuecomment-315601713)

[PS. I'll cross-post this to the other discussion. Implementation detail fluff has distracted from essence of discussion]

**Comment by dominictarr** [comment]
um, I'm sorry but why do you think we havn't been thinking about all that stuff?

If you came on ssb and talked to people I think you'd see not only on the same page but reading/writing the same book. Most of the best ssb content is on ssb, not the web, so you just might not have found it yet if you don't have patchwork installed ;)

http://github.com/ssbc/patchwork
get a invite code from here: https://github.com/ssbc/scuttlebot/wiki/Pub-servers

**Comment by aschrijver** [comment]
On the contrary, I didn't doubt for a second, that you'd had given these things much thought!

But still these were the observations I made as an outsider discovering the technology field. I experienced newcomer feedback often as very refreshing, so I took the time to give mine.

It is reassuring and good to hear you have things clear and well-documented.
You keep it well hidden, which is maybe less good, but that depends.

Realize that someone doing technology research has on average about a week to create a shortlist, then starts elaborating on the top entry of that list. If that is a match and SSB was not on the top, you may end up being mentioned in the 'Related technologies' section of the design doc of the new project, nothing more.

Finally the executive summary is a bit generic, as it applies to all candidates equally. I've chosen Dat as top entry of my list, therefore the long feedback thread is tailored to them. But I lot of points I touch on could be of equal value to you.

PS You have made me curious, so if I find time I will install the software and search for it.

**Comment by dominictarr** [comment]
If you are trying to evaluate the things, might be a good idea to use each of them not just read about them.
it's not hidden, it's just we are using the thing to build the thing and discuss the thing,
you are just still on the old internet! ;)

**Comment by aschrijver** [comment]
Ha ha, okay, you've got me...old internet here.. I appreciate that response :)

**Comment by aschrijver** [comment]
BTW The original discussion has been seriously cleaned up. Now mostly pertaining to Dat, but FYI: https://github.com/datproject/discussions/issues/58

I have convinced some project members it might be useful to create a message-based abstraction layer.

**Comment by dominictarr** [comment]
@aschrijver I don't think I've seen you on patchwork yet, is that correct?

**Comment by aschrijver** [comment]
Yes,  correct. Not yet :)
