### ISSUE TITLE
Provide more design, specification and operational documentation

### ISSUE THREAD

**Issue by aschrijver** [ssbc/secure-scuttlebutt#181]
As a newcomer to decentralized computing I was recently comparing between SSB and [Dat Project](https://datproject.org).

Even though SSB seemed closer to my use case (social networking) I decided to more closely evaluate Dat instead of SSB for following reasons:

- Dat has more of a specification effort and documentation on wire protocol and archive formats
- The extend of Dat documentation led me to believe it could be re-purposed to fit my use case
- I couldn't figure out the operational requirements of a Pub server in terms of bandwidth, storage, information exchange and costs involved with hosting a Pub server (e.g. in AWS)
- I couldn't find good documentation of running a flock of private Pub servers and how they would interoperate

Just saying, providing more in-depth documentation like this, would make it easier to adopt your technology.

**Comment by dominictarr** [comment]
@aschrijver thanks that is very specific and useful feedback! Life would be so much easier if everyone could give feedback like this!

**Comment by aschrijver** [comment]
np :thumbsup:
