### ISSUE TITLE
Implementing a decentralised sorting mechanism?

### ISSUE THREAD

**Issue by tusharmath** [ssbc/secure-scuttlebutt#187]
I am trying to build an application where I have a lot of users and each user has a score. Every 5 minute the scores change for each one of them. These users are interested in seeing their relative ranking based on their scores.

How should I architect a solution using an append only log? 
PS: Consider I have close to a million users and right now I am running this logic over at spark in a centralized manner.

**Comment by gardner** [comment]
It doesn't seem like an append only log is the right storage mechanism for a scoreboard. Do you need to rewind back through time to see scores at different times? Is there a trust aspect to the system that you gain from having previous scores stored? (i.e. p2p validation and verification)

**Comment by tusharmath** [comment]
@gardner I do need to rewind back and see thru time, how the ranks have changed.
