### ISSUE TITLE
Snap Package Available?

### ISSUE THREAD

**Issue by skellat** [ssbc/secure-scuttlebutt#188]
Would a [snap package](https://www.ubuntu.com/desktop/snappy) for the software be available potentially?  For software with parts that get updated frequently this allows for more atomic-level updates and more frequent updates even in Ubuntu without waiting on package archive freezes.  There are [instructions available](https://docs.snapcraft.io/build-snaps/) and snaps are apparently supported on multiple Linux distributions.

**Comment by dominictarr** [comment]
oh, we got this PR, https://github.com/ssbc/scuttlebot/pull/443 but I was too busy to merge...
