### ISSUE TITLE
Future React Native support?

### ISSUE THREAD

**Issue by marcusfelix** [ssbc/secure-scuttlebutt#193]
First, awesome project!

I think this concept will be very handy on mobile. You guys expect to port this to React Native JS engine any time soon?

Thx

**Comment by staltz** [comment]
- https://github.com/ssbc/react-native-scuttlebot
- https://github.com/ssbc/react-native-ssb-client
- https://github.com/ssbc/react-native-ssb-shims
- https://github.com/ssbc/react-native-ssb-client-keys
- https://github.com/staltz/mmmmm-mobile/
