### ISSUE TITLE
[Question] Multiple feeds for one key?

### ISSUE THREAD

**Issue by juancampa** [ssbc/secure-scuttlebutt#195]
## Question

Does SSB support multiple feeds with the same public key? For example:

```
const id = getMyPublicKey();
const myFeedA = createHistoryStream({ id, name: 'feed-a' });
const myFeedB = createHistoryStream({ id, name: 'feed-b' });
```

I'm very new to SSB but from reading the docs it seems like feeds are identified by their keys which I guess means one feed per key. But maybe I'm missing the point and there's another way to think about this.

Use case: I'm building a pub/sub system where publishers have different unrelated events they can publish. I want to avoid subscribers getting unrelated events

**Comment by juancampa** [comment]
More context. I'm currently using PouchDB which can replicate to another PouchDB instance with a filter function: only documents that pass the filter are replicated.

I'd like to *ahem* replicate this behavior with SSB

**Comment by juancampa** [comment]
Also, I don't think I can replicate the filtered replication itself because of the how each message is validate with the previous one but I could, in theory, create pre-filtered feeds

**Comment by ahdinosaur** [comment]
hey @juancampa!

> Use case: I'm building a pub/sub system where publishers have different unrelated events they can publish. I want to avoid subscribers getting unrelated events

why not create a new key for each feed?

**Comment by juancampa** [comment]
> why not create a new key for each feed?

I could do that but then I'd need a separate ID to tie those together. The publisher is semantically one identity so it would be nice to refer to it by its public key signature instead of an artificial ID.

Having an artificial ID also introduces a security issue: someone could change the public keys belonging to the ID.

I guess one way to do it is having one "meta" feed that contains the public keys of the "secondary" feeds. Secondary feeds are the ones with the actual messages.

Does this sound rational? Have you seen a similar use case? Thanks for the reply!

**Comment by timjrobinson** [comment]
@juancampa Having one publisher feed that just publishes the id's of the secondary feeds sounds logical to me. 

Feed items just keep a hash of the previous item in the feed. So you can have a feed of only the filtered documents, the items will just have different hashes than the unfiltered feed.
