### ISSUE TITLE
SSB as backend for a federated blogging platform?

### ISSUE THREAD

**Issue by bmiller59** [ssbc/secure-scuttlebutt#196]
I am interested in using SSB as a backend for a federated, distributed blogging platform. 

In my searching I have not found any SSB based platforms, nor was I able to find any federated blogging platforms in general. Is anyone aware of such a project? No need to reinvent the wheel...

If not, anyone have suggestions on a good way to structure and implement such a project? For efficiency I was thinking of an integration with an existing blogging frontend with a nice UI.

One idea I had was to leverage hexo.io. Advantages:

- nodejs based like SSB
- popular and widely used
- does not have a complicated database structure like wordpress. You just write markdown for posts.

Any redirection, encouragement, or collaboration is welcome. Thanks.

**Comment by evbogue** [comment]
@bmiller59 This isn't really an issue with `secure-scuttlebutt`, and might be best had as a conversation on the ssb network itself. 

But to answer your question, the closest possible match to the application you're describing is probably TickTack: https://www.scuttlebutt.nz/applications.html#ticktack

**Comment by dominictarr** [comment]
yes ticktack has a blog model, you'd just need a web viewer, for it and you'll have a federated blog engine.
/cc @mixmix

**Comment by bmiller59** [comment]
Thanks for the suggestions. I will look further into ticktack and close this ticket!

**Comment by bmiller59** [comment]
Sorry to post this here, but I've had no luck finding @mixmix on patchwork from the public pubs I've joined. I've tried to clone into ticktack from the SSB url provided at scuttlebut.nz by 
`git clone ssb://%wnNDjViKYZH+RWpbNzDXR2oxLWmTagvvFBjy97Zko4I=.sha256`

After running patchwork and installing git-ssb, but I am getting this error:

`fatal: did not receive expected object d5f19d89b308d36ee9e27b912015b0f75ec2f03f                                                                 fatal: index-pack failed`

I am excited to collaborate in SSB space, but getting plugged in is difficult. Perhaps there could be a discovery service on the HTTP web for finding people or git repos...some kind of crawler-indexer?

Thanks for your help with this.

**Comment by arj03** [comment]
ssb-viewer can now display blogs written in TickTack :-)

**Comment by mixmix** [comment]
Did not know! Did someone use scuttle-blog or just roll their own?

Brendan there is a public repo with installers on github now
github.com/ticktackim/ticktack-workplan/releases
Find me on twitter at @whimful if you have any trouble

**Comment by arj03** [comment]
I started with scuttle-blog actually, but the problem is that ssb-viewer needs a good overhaul and it was just easier to hack in it the same way the rest is done. I really like the scuttle-blog pattern. I hope that other pieces in the scuttleverse will get the same threatment.

Example: http://between-two-worlds.dk:8807/%RTXvyZ2fZWwTyWdlk0lYGk5sKw5Irj+Wk4QwxyOVG5g=.sha256

**Comment by mixmix** [comment]
Good work! I went looking for the ssb-viewer repo last night and couldn't
find it. Where does it live?

**Comment by arj03** [comment]
Its on git-ssb. Check out the calm branch, it has all the latest goodies.
