### ISSUE TITLE
[Question] Can I help with iOS development?

### ISSUE THREAD

**Issue by garsdle** [ssbc/secure-scuttlebutt#197]
Hey guys, iOS dev here 😬👋

I've seen that there are some efforts to make ScuttleButt in react native though it seems to be problematic; what about going full native? Or maybe reusing some of the modules by using JavaScriptCore?

I've been intending on making a decentralized chat that used bluetooth, wifi direct etc.. but I feel like scuttlebutt is even better. Maybe I'm underestimating the magnitude of the undertaking...

Wouldn't it be cool if messages could sync in the background via bluetooth though?  I do background BLE messaging in my old app AirChat. I think mobile is the obvious next step.

Anyways I love scuttlebutt so far and want to contribute!

**Comment by staltz** [comment]
Hey, we'd love to have some help on other mobile efforts. There's a lot of discussion about mobile already on scuttlebutt itself, so find us there and we can talk more :)

**Comment by garsdle** [comment]
Awesome :)

I am on scuttlebutt. Any channel in particular?

**Comment by garsdle** [comment]
NM I saw your message. Cheers
