### ISSUE TITLE
Using secure-scuttlebutt as an append-only database

### ISSUE THREAD

**Issue by ragjunk** [ssbc/secure-scuttlebutt#201]
I have a use-case for append-only database and secure-scuttlebutt serves the purpose very well. The only problem is that the "feed" is owned by a "single" public key (user or node). In my use case, multiple "clients" can send messages to one or more of the "feed" owners for persisting the messages in respective feeds. So, if the node owning the feed is offline, the message cannot be written. Is there a way this use-case can be addressed without sharing the keys with multiple nodes? Currently, scuttlebutt allows replication, but there seems to be no way some other node can "takeover" to write the messages into the feed. Any pointers is appreciated.

**Comment by ahdinosaur** [comment]
hi @ragjunk, if you simply want an append-only database to use for any use case, you might be interested in [`flumedb`](https://github.com/flumedb/flumedb).

**Comment by ragjunk** [comment]
Thanks for the prompt response @ahdinosaur, @dominictarr. I looked at flumedb also, but my use case requires _replication_ so the "feed" (the node hosting it) doesn't become a single point of failure. I am comparing scuttlebutt against Dat's [Hyperdb](https://github.com/mafintosh/hyperdb) which has an "authorize" API to authorize a peer to write to the same feed. So, you can setup a few replicating peers that will be able to accept the "writes" as well as replication streams, so there is no single point failure for the data in the feed. With this setup, the clients can choose to connect to any of the peers that advertise the feed and be able to read and write to that peer. I found scuttlebutt's design is more natural, except for this particular issue on single point failure. I understand that scuttlebutt is not designed to serve as a database, but its "append-only" design and the security guarantees that come with it are very powerful. Any thoughts on this is appreciated.
