### ISSUE TITLE
Use webrtc as transport instead of TCP

### ISSUE THREAD

**Issue by traverseda** [ssbc/secure-scuttlebutt#210]
Using webrtc as a default transport would let web-based clients communicate with one another, peer-to-peer, without an the user needing to install a desktop app.

**Comment by staltz** [comment]
But you also need a database :)

**Comment by traverseda** [comment]
Yeah, mostly I didn't want to open up a bunch of issues for the different parts untill I saw how this was received. IndexedDB is available in most relevent browsers now, and there are filesystem implementations built on top of it. I don't imagine porting flume to be a huge problem.

As an aside, I missed #179 during my search, because I was looking specifically for webrtc.

**Comment by staltz** [comment]
We've had efforts to build scuttlebot on top of indexeddb but it's pretty bad quality when compared to leveldb. I haven't been involved with the implementation but I heard there are a lot of problems with it. And regarding WebRTC, @pietgeursen is working on doing that

**Comment by cryptix** [comment]
Instead? I find that a bit over the top.

IIRC one also needs a signaling server to make a sctp-wrapped-in-udp connection. Pubs could do that but last time I checked we wanted to reduce their importance..

**Comment by dominictarr** [comment]
@traverseda we do intend to support webrtc (and utp) as well as tcp and ws, see
https://github.com/ssbc/multiserver/
but there are some hoops to jump through, and I've heard reports that webrtc is really heavy (you can crash a browser by just by creating lots of connections)

Also, indexeddb is slow in my measurements, but if we had a polyfil for https://github.com/flumedb/flumeview-reduce and https://github.com/flumedb/flumeview-level we could at least get something running. Any help here would be much appreciated! getting the secure-scuttlebutt tests passing in a browser context should be the first objective

**Comment by Serkan-devel** [comment]
But isn't WebRTC built on top of TCP? And what database does ssb use?

**Comment by fermuch** [comment]
@Serkan-devel WebRTC can work with both UDP and TCP. Peer connections AFAIK use SCTP, which runs on top of UDP.
