### ISSUE TITLE
[question] private messages

### ISSUE THREAD

**Issue by pgte** [ssbc/secure-scuttlebutt#216]
Hi,

I was skimming through the docs and I couldn't find any details on how you implement encrypted messages between two peers. Is this defined in the protocol?
Also, are private group messages possible or being discussed?

**Comment by pgte** [comment]
Oh, this is a beautiful document, thank you!

**Comment by dominictarr** [comment]
@pgte note that there are a few known problems with this design: https://github.com/auditdrivencrypto/private-box/issues/5 so we will switch to something more like: https://github.com/dominictarr/group-box (consider that a draft, though)
