### ISSUE TITLE
getClockRange

### ISSUE THREAD

**Issue by arj03** [ssbc/secure-scuttlebutt#224]
As far as I can understand ssb-ebt, it calls getAtSequence for each messsage. Benchmark 07 clock-dump in bench-ssb shows that this can be rather slow. Its around 33 seconds versus 6 for normal sbot read of 100k messages. So I thought I would implement something like: 

```
  db.getClockRange = function (from, to) {
    //will NOT expose private plaintext

    return pull(
      db.clock.read({
        live: false,
        gte: from,
        lte: to,
        keys: false,
        values: true,
        seqs: false
      }),
      pull.through(function (value) {
        return u.rebox(value)
      })
    )
  }
```

And then use it like:

```
  pull(
    Many(Object.keys(clock).map(function (key) {
      return db.getClockRange([key, 1], [key, clock[key]])
    })),
    pull.drain(function (msg) {
      log(1, ++i % 10000 == 0)
    }, function (err) {
      console.log(err)
      log(0, true)
    })
  )
```

But this is slower than getAtSequence, much slower. Around 56 seconds. I don't understand why.

**Comment by dominictarr** [comment]
hmm, these both require streaming level reads, which also include quite a bit of parsing, etc. is the read 100k messages you are talking about is straight from the log?

**Comment by arj03** [comment]
Its [this](https://github.com/ssbc/bench-ssb/blob/master/07-clock-dump.js). I just replace [line 14](https://github.com/ssbc/bench-ssb/blob/master/07-clock-dump.js#L14) with the code above.

**Comment by arj03** [comment]
I get i now. Values makes the call get values the same way, one by one. Gonna continue this investigation.
