### ISSUE TITLE
using addMap() seems to break replication

### ISSUE THREAD

**Issue by christianbundy** [ssbc/secure-scuttlebutt#225]
I'm unsure whether this is a problem with secure-scuttlebutt or scuttlebot, but using the `addMap()` function seems to stop my messages from being synced to other peers. My intuition is that Scuttlebot might be hashing (or broadcasting?) the mapped data rather than the original, but I'm not familiar enough to understand exactly what's going on.

---

If the above *is* the case, maybe we'd need a way for critical message infrastructure like replication/verification to opt out of any message modifications?

**Comment by cryptix** [comment]
This is about your type:blob messages, right? I only looked at it briefly but the only case I could think of why you wouldn’t be able to sync those out is if your createHistoryStream or ebt replication sent out messages with the map applied... if it does this you sent the wrong content for the signature...

The unaltered message (just with the type and blob reference) should be totally fine and go out..

do other messages still get out?

**Comment by christianbundy** [comment]
Yeah, any messages before the mapped message (blob) went out just fine, but the blob and all messages afterward didn't get out at all.

**Comment by cryptix** [comment]
buut.. which key / sequence is that?

I got `%SUB6xPT0IO2kAGIYamCAjWApx+TDzsCYotU+EZkPWNE=.sha256` as seq:6094 and the latest I got from you 6131.

**Comment by christianbundy** [comment]
My messages are getting out now because I've disabled the plugin. The map only happens on read, so as soon as I disabled the plugin and restarted it started replicating all of my messages again.

It seems to me that we need to give an option to disable `addMap()` functionality on infrastructure that's going to hash/replicate/etc.

**Comment by cryptix** [comment]
honestly, I thought this was just applied on read by clients that want it.

Yes, enabling this by default for other clients will get you in trouble with replication.

**Comment by christianbundy** [comment]
Yeah, the idea is that you'd be able to do some changes behind the scenes rather than having to make changes to every single plugin. For example, if you wanted to do a [cloud-to-butt](https://github.com/panicsteve/cloud-to-butt) find+replace, there's no easy way to do that. With `addMap()`, you'd do something like:

```js
ssb.addMap((val, cb) => {
  if (val.value.content.type === post) {
    val.value.content.text = val.value.content.text.replace(/cloud/g, 'butt')
  }

  cb(null, val)
})
```

Do you know why the private unboxing code isn't having this problem? Seems like it's doing the same sort of thing, so I'm wondering what the difference is.

**Comment by cryptix** [comment]
Hmmm.... my guess would be that the private unbox you mentioned doesn’t use this addMap feature but I’m a bit out of my depth here.

**Comment by christianbundy** [comment]
No problem, the `addMap()` was designed to work similarly to the private unbox, but it sounds like I've done something wrong. I'll keep poking around, thanks for your help!

**Comment by cryptix** [comment]
beware: halved finished thinking between stuff and definitely not easy but might be interesting to look into refactoring the private unbox into using this if it is so similary in spirit and features... those should also be tested which _might_ help to untangle this?

**Comment by christianbundy** [comment]
I think I've got a pretty good understanding of the problem now. The important functions here are [`rebox()` and `reboxValue()`](https://github.com/ssbc/secure-scuttlebutt/blob/37007420db0e94521416b4f92198e177b95f7f0d/util.js#L46-L66), which seem to be the "clean up your room before mom gets home" functions that sweep up any trace of the private unboxer and revert the changes. Unfortunately, these are only added to [`db.get()`](https://github.com/ssbc/secure-scuttlebutt/blob/37007420db0e94521416b4f92198e177b95f7f0d/index.js#L67-L89) but don't trigger on `db.stream()`, so when we add maps we automatically fail [this test](https://github.com/ssbc/secure-scuttlebutt/blob/54af87dda481cc303390c57305bb7d93c42b5b46/test/append.js#L103) because it's a stream.

To make things more complicated, most of our "reboxing" logic is specific to the private unboxer, so I think we're going to need a more general solution. I think the best course of action would be:

1. Standardize on a metadata location like `value.meta` so we don't have to remove arbitrary properties (currently "private", "cyphertext", and "unbox"), which will only increase in complexity over time.
2. Specify that transformers (main_unboxer and addMap, currently) must record the original data in a standard location, like `value.meta.original.content`, when making a modification, so that we can rebox the values correctly.
3. Modify the tests so that `db.stream()` doesn't complain about `value.meta` being added, *or* call the reboxer on streams.

**Comment by christianbundy** [comment]
Btw @cryptix that was a great call, I don't think I would've found the solution without that suggestion. Thank you!
