### ISSUE TITLE
Performance regression in 18.5

### ISSUE THREAD

**Issue by arj03** [ssbc/secure-scuttlebutt#232]
@christianbundy I was testing my performance improvement in #223 but could not understand why it was slower. Didn't make any sense. Turns out I was testing 18.4 against 18.5 + my patch. It seems as if the mapper stuff added here: https://github.com/ssbc/secure-scuttlebutt/blob/d77727aa73a070fa45dc9f67fe2e42002d2dc9d1/minimal.js#L97 takes up quite some time. On my machine running 11-sbot-replicate-ebt.js from https://github.com/ssbc/bench-ssb/ is 172 seconds in 18.5 and 149 seconds in 18.4.

**Comment by christianbundy** [comment]
I don't think I benchmarked `11-sbot-replicate-ebt.js`, I only [benchmarked `06-ssb-read.js`](https://github.com/ssbc/secure-scuttlebutt/pull/222#discussion_r222475310) and it seemed to have the same perf.

I wonder whether this is resolved by #228 (or *maybe* #227). The idea behind `addMap()` was that we were going to move the unboxer code from the codec to flumedb, but currently `master` has the overhead of the maps without actually using it.

**Comment by christianbundy** [comment]
Still doesn't look great:

- **`~18.4.0`:** 34.59 seconds
- **`map-unboxer-meta`:** 40.9406 

Looks like it still takes 18% longer during replication. Any idea why that might be? I'd imagine that replication would have similar benchmarks as reads, but apparently that's *very* incorrect.

**Comment by arj03** [comment]
Well the test does actually move quite a lot of data in and out of flume as there are two ends to this, instead of just reading as in the sbot-read case.

**Comment by christianbundy** [comment]
I'm a bit confused about this regression. I'm having the same performance when remove the codec unboxer and replace `chainMaps()` with:

```js
(msg, cb) => cb(null, db.unbox(msg))
```

Unless I'm doing something *very* wrong, this seems to suggest that our asynchronous handler in flumedb is significantly slower than our synchronous codec unboxer. Could the callbacks really be responsible for the slowdown?

**Comment by arj03** [comment]
Seems like it. Both 18.4 and 18.5 uses flumedb 0.5.1 so it appears that the only diff is that you now pass chainMaps to flumedb.

**Comment by arj03** [comment]
Maybe its [get](https://github.com/flumedb/flumedb/blob/master/index.js#L67). https://github.com/ssbc/bench-ssb/blob/master/06-ssb-read.js#L12 does not use this (values: false) but ssb-ebt does. https://github.com/ssbc/secure-scuttlebutt/blob/master/index.js#L144

**Comment by christianbundy** [comment]
That would make sense, since ssb-read is using a [happy path](https://github.com/flumedb/flumedb/blob/master/index.js#L51-L52) that doesn't even trigger the map whereas ssb-ebt is forced into [this operation](https://github.com/flumedb/flumedb/blob/master/index.js#L56-L64). I just tried (manually) setting paramap's width to `1` and I'm averaging 35 seconds. I think our problem is that the unboxer is working in parallel, which might not be the most optimal.

Should we modify flumedb to use a [non-parallel map](https://github.com/pull-stream/pull-stream/blob/master/docs/throughs/async-map.md), or is there something that we can do to make the unboxer more paramap-friendly?

**Comment by arj03** [comment]
hmm, can you try with a low number. Say 5 or 10 and see how that compares.

**Comment by arj03** [comment]
On my machine 10 seems to work better than 5 and 1. Both all them them are much better than before.

**Comment by arj03** [comment]
asyncmap is as good as paramap 10 on my machine, so I think it would be nice to do a new release of flumedb with flumedb#20 merged. And them bump dep in secure-scuttlebutt to get 1.0.x.

**Comment by christianbundy** [comment]
Sweet, that sounds like a good call to me. I'll wait to hear what @dominictarr thinks.

> And them bump dep in secure-scuttlebutt to get 1.0.x.

Should we just do this now? As long as we `^` or `~` then we'll get the flumedb update automatically. I can either make the PR or approve it.

**Comment by arj03** [comment]
That would be a good start I think. Thanks @christianbundy

**Comment by arj03** [comment]
Been testing master of secure-scuttlebutt today, so far no problems smooth sailing

**Comment by dominictarr** [comment]
yes, so if no width is set, then it is basically infinite width: 
https://github.com/pull-stream/pull-paramap/blob/master/index.js#L31
I'm updating pull-paramap to set a default width of 16.

maybe that is a really bad idea? since the unboxer is not really async, paramap adds a lot of clutter (and arrays and such) that don't lend any benefit in those cases. I think we should really benchmark pull-paramap I don't think it's been benchmarked on it's own, so I'm sure it could be improved.

**Comment by dominictarr** [comment]
oops, I wrote "maybe that is a bad idea" before I wrote "updating to set a default width" I meant not having a default was the bad idea.

I think I'd be inclined to continue to use paramap but with a reasonable default.
Hmm, I'm not detecting a difference between map-unboxer-meta and 18.4 or 18.5 running 11-sbot-replacate-ebt.js I get 66 seconds for all

**Comment by arj03** [comment]
@dominictarr strange that it is the same performance on your machine if its worse on both mine and christianbundys? The reason 10 ebt is slower should be: https://github.com/ssbc/secure-scuttlebutt/issues/232#issuecomment-432972137. I don't see the reason for doing paramap if it doesn't really give us anything. So I'm more in favour of https://github.com/flumedb/flumedb/pull/20.

**Comment by dominictarr** [comment]
@arj03 okay, lets merge https://github.com/flumedb/flumedb/pull/20 we can always switch back later if we want

**Comment by christianbundy** [comment]
Let me know if you need anything from me. :+1: I think all we need to resolve this is a merge and NPM publish of flumedb.

**Comment by arj03** [comment]
Done.
