### ISSUE TITLE
18.5.1

### ISSUE THREAD

**Issue by arj03** [ssbc/secure-scuttlebutt#236]
Something strange is happening with messages in my log with 18.5.1. Looks as if messages are double encoded with key value inside the value property. I have unpublished the version from npm.

**Comment by arj03** [comment]
The offending message was %tZMi4Cs61AlUwJ4+JMbVRFKbaka5146+6ELzX54XdkA=.sha256. I don't have that one on my pub. I'm going to leave my machine running to resync.

**Comment by christianbundy** [comment]
FWIW, I don't have it either. Just to clarify, you're seeing messages that look like this?

```js
{
  "key": "%G0h7k51CxXygl+QpOcVIIgpTeZ7SoGAiZaLQ8P0OKP8=.sha256",
  "value": {
    "key": "%G0h7k51CxXygl+QpOcVIIgpTeZ7SoGAiZaLQ8P0OKP8=.sha256",
    "previous": "%h0lKNOLzvp2P9Bdy0bETXeShEAfAz5SFag81+Taa554=.sha256",
    "author": "@+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=.ed25519",
    "sequence": 6708,
    "timestamp": 1540851770015,
    "hash": "sha256",
    "content": {
      // ...
    },
    "signature": "4/Qgo7lpe09JRJVgvQN57nrjohKjG0B+y68HmBc7q0zQt1tXoYMpofyjE53nLEqJ2mAUUWi/x3R+CmfHn2hACQ==.sig.ed25519"
  }
}
```

That's definitely funky. I've seen lots of variables to refer to the message object and the value object, maybe it would be wise to standardize on `msg` and `msgValue` or something if we find out that it's something as simple as the wrong variable.

**Comment by christianbundy** [comment]
This seems to be the only commit with behavior changes since 18.5.0: https://github.com/ssbc/secure-scuttlebutt/commit/1c18fd0c44e02e7deea52172ffc99c77fd9d961f

I wonder whether this is a problem with one of our dependencies or (hopefully) just a weird message that somebody published.

**Comment by dominictarr** [comment]
@arj03 the thing that might affect this could be ssb-validate. It also seems related to the work you have been doing regarding the https://github.com/ssbc/secure-scuttlebutt/pull/233

**Comment by arj03** [comment]
@christianbundy yes it looked like that.

@dominictarr Yeah but I wasn't running any of that code. I was just upgrading secure-scuttlebutt after pushed and started sbot and it got that wierd message right away. But yeah, looks like something like that could be the problem. Strange.

I'm finally back in business (restoring from network takes ages :?), will do backup this time and some more testing ;-)

**Comment by arj03** [comment]
Currently running with no problem just linking in 18.5.1 locally. I'll keep it running for the next day before trying to push that version again to npm. Wonder what the hell happened as that message doesn't seem to exist.

**Comment by christianbundy** [comment]
![twilight zone](https://media.giphy.com/media/tkvD32sUDfBD2/giphy.gif)

**Comment by arj03** [comment]
Pushed to npm now as 18.5.2. I must have had some deps wrong because it doesn't make sense to see that behaviour and it hasn't happened after two days of active usage. Sorry for the noise and thanks for the help.
