### ISSUE TITLE
inconvenience - no easy way to rebuild plugin dependencies   

### ISSUE THREAD

**Issue by frankiebee** [ssbc/secure-scuttlebutt#241]
when upgrading node versions sbot cant run because plugin modules are compiled against my old version this is a pain 😅 maybe i'll come up with something before then but it would be nice if this was fixed

**Comment by frankiebee** [comment]
oh woops wrong repo my bad y'all 😅

**Comment by dominictarr** [comment]
for modules installed via `sbot plugins.install`, you could do `cd ~/.ssb && npm rebuild` that should do it.
