### ISSUE TITLE
Merkle Tree Logs

### ISSUE THREAD

**Issue by dominictarr** [ssbc/secure-scuttlebutt#27]
Idea: if we where to use merkle tree logs, then it would be possible to securely replicate a portion of a feed.

The messages would still contain a link to the previous message, but the messages would also be hashed into a binary tree. Then I can request the 5th message, this would point to the hash of the  first 4 messages (since 32 is a power of 2)

it would be 

``` js
hash(
  hash(hash(msgs[0]) + hash(msgs[1])) +
  hash(hash(msgs[2]) + hash(msgs[3]))
)
```

Then, if I requested message 1 later, I could verify it was consistent with what I was given last time.

Currently we use only use a singly linked list. This is simple, but can only be used to verify that messages are part of a log if you have the entire log.

I suspect that this would be very useful on the edges of the network. Maybe you want to retrive a reply that a friend of a friend of a friend made? If you did this for everyone on reddit it would be too much resources - but if you got a few messages from them, it would still be highly secure, because you would be able to prove those messages where part of the same tree, using just a few extra hashes...

This would mean rewriting most of the validation code.

**Comment by krl** [comment]
@dominictarr hi, @pfraze directed me to this discussion, just want to point you towards a datastructure proposal i vizualised to explain it to myself and others.

https://github.com/krl/notes/wiki/append-only-finger-tree

i think something like this could work very well for logs

**Comment by krl** [comment]
So, if the new message does not refer to the prior message, but to the last root hash.

Validation would then be to take the previous known hash, apply the append operations, and see if all the messages refer to the right roots along the way.

**Comment by dominictarr** [comment]
@krl can you do a sparse verification? like if I have the 1st, and 100th message, and then i get a 50th message can i verify that it's actually in that chain without pulling down everything?

**Comment by krl** [comment]
yes, you can have a merkle-proof that message nr 50 actually is contained in the root-hash of nr 100. you would just have to ask for uncles leading to root-hash 100 for message 50. 

Also note, in this scheme, with 100 messages, you would have message 1 and 100 directly in the root node.

**Comment by carloslfu** [comment]
hello, anyone have progress on this topic? I am highly interested and want to contribute.

**Comment by dominictarr** [comment]
@carloslfu that is great! This would be a pretty difficult thing to add because you are getting right into the heart of ssb. It can be done, but we'd need a _strategy_. It's important to get a useful, usable result in the short/medium term - what are you hoping to achive? lets figure out a way to get there!

**Comment by ahdinosaur** [comment]
oh wow cool issue.

> but then you would be able to request the latest message, the first message, and then any message in the middle and prove that it was part of that log.

from my perspective (still keen to hear from @carloslfu), it seems this helps solve two problems at the moment:

- out-of-order messages (being able to request a specific message from a log that you aren't following),
- initial syncs (starting from the latest so you get immediate content without the lag)
- partial syncs (maybe you don't even need to fetch _every_ message from my log if we just met).

/cc @mmckegg

**Comment by carloslfu** [comment]
Hi @dominictarr and @ahdinosaur I am hoping to achive more faster inital syncs and partial syncs. Also would be nice as @ahdinosaur says to have out-of-order messages. For now I am learning about the protocol and reading the code. I will experimenting and doing some proofs of concept  as soon as possible.

**Comment by AljoschaMeyer** [comment]
For future travelers, here is a more recent, somewhat detailed discussion on merkle trees: https://viewer.scuttlebot.io/%25L9m5nHRqpXM4Zkha1ENTk5wNOXQMduve8Hc9%2BF0RLZI%3D.sha256
