### ISSUE TITLE
Improved messagesByType: multiple types, added since time X

### ISSUE THREAD

**Issue by pfraze** [ssbc/secure-scuttlebutt#44]
Applications will need to fetch the messages, update their local state, then fetch any new messages since the last fetch. As a practical example, Phoenix needs to construct the profiles of users by fetching all the `profile` messages and getting the last `nickname` value published by a given user.

There's two tricks here. First, we need to be able to fetch multiple message types at a time. The phoenix feed view, for instance, will probably want everything in https://github.com/pfraze/phoenix/issues/102 (init, text, profile, follow, pub).

Second, we need to be able to get messages that have newly arrived. If I receive a message at 6pm that was published at 4pm, and I say "give me everything that's arrived since 5pm," then I'd want that message published at 4pm.

**Comment by dominictarr** [comment]
this is implemented now
