### ISSUE TITLE
Trustless trust

### ISSUE THREAD

**Issue by pocesar** [ssbc/secure-scuttlebutt#65]
Would be nice that ssb could create a confirmations field to ensure that the data in there is trusteable and were verified at least `x` times by other nodes. This could make the replicated data much more reliable, since you might or not know peers, that differ from public initial ones, that delegate the other nodes in the network that you are able to connect to

**Comment by rabble** [comment]
If you can't make the on boarding process work then patchwork is a joke and will never catch on. Onboarding is a major focus of scaling social networks and if you ignore it nothing else matters.

**Comment by dominictarr** [comment]
@rabble patchwork has come along significantly since we had this discussion, I'll email you an invite code so that you can judge the on-boarding process properly.

**Comment by dominictarr** [comment]
@rabble sorry the email on your github profile didn't work... where can I send it?

**Comment by pfraze** [comment]
I sent @rabble an invite in IRC.
