### ISSUE TITLE
whoami optional param for keypair ownership challenge

### ISSUE THREAD

**Issue by pfraze** [ssbc/secure-scuttlebutt#71]
Third party apps need proof that the local machine owns the claimed keypair. I propose we add an optional first param (the challenge) which, if provided, will be signed by ssb and returned in the whoami response.

eg

```js
var challenge = Math.random()
ssb.whoami(challenge, function(err, id) {
  if (!ssbKeys.verify(id.pubic, id.sig, challenge)) {
    alert('Hackers afoot!')
  }
})
```

**Comment by dominictarr** [comment]
this is no longer necessary since we have a secure channel protocol that authenticates the other party.
