### ISSUE TITLE
reject too-big messages

### ISSUE THREAD

**Issue by dominictarr** [ssbc/secure-scuttlebutt#74]
oops, @pfraze created message `H6yP9cn3T7D4lB/Yf9ndjVD9gRPwBFImhjsldFtS1+0=.blake2s` which is way too and should not have been validated.

now there are two problems: fix validation to disallow such messages. clean the current instances so that invalid messages are removed.

**Comment by pfraze** [comment]
yeah lets just discard that (my) feed and plan not to do that again

**Comment by dominictarr** [comment]
what should have happened: the messages before that should have been accepted, but that messages (and thus any messages after that) should be rejected.

**Comment by pfraze** [comment]
looking at scuttlebot's replication, it's a pretty straight pipe from the peer's history stream into a local write stream. is there validation occurring somewhere?

**Comment by pfraze** [comment]
oh yes -- in the `.add` function

**Comment by pfraze** [comment]
this has been handled
