### ISSUE TITLE
ranking names/keys by link analysis

### ISSUE THREAD

**Issue by dominictarr** [ssbc/secure-scuttlebutt#75]
pagerank uses a straightforward ranking system, where pages linked are ranked by the sum of ranks of the pages that link to them. pagerank is calculated in an iterative process, all pages start off with equal rank, and then rank flows along the links. thus, if many pages link to you, you get a higher rank, or a few very highly ranked pages link to you you get a higher rank.

check out the images on the wikipedia page rank article https://en.wikipedia.org/wiki/PageRank

Since it starts off with all pages being equal, pagerank is vunerable to spam - blackhat seoers create many fake pages which then link to a target page, inflating it's rank.

Google calculates (originally did, at least) a global pagerank value persite, so that it only has to do one pagerank calculation for the whole webgraph. there are some algorithms that attempt to prevent spam, by starting with a known quality set of pages, for example, trustrank: https://en.wikipedia.org/wiki/TrustRank and then allow trust to flow out of those pages as in pagerank. This essentially amounts to doing pagerank but with a non uniform initial state (some sites start off with higher initial rank)

We could use a similar approach with ssb. We can't provide a known good set, because that would be centralization, but since each user will need to calculate the rank for their peers, they could use an initial state where they trust themselves completely, and then let trust flow out from the links they have created - giving each user subjective ranks for their peers. My hunch is this would prevent much spam, because a spammer would have to trick to into explicitly trusting them, which would be much harder than just generating fake accounts.

**Comment by jtremback** [comment]
Does this involve the user rating other users in some way, or is it purely based on the fact that there is a link? Something like this, if executed on a "sliding scale" instead of just to block spam, could serve a similar purpose as Facebook's news feed algorithms. 

What pieces of information in SSB would indicate trust?

**Comment by dominictarr** [comment]
@jtremback currently we are using explicit trust statements - effectively saying things like "@jtremback is a good guy". You could also use implicit statements, like, depending on code that someone wrote implies that you trust them to some degree, but there isn't really anything in ssb that is like that yet.
