### ISSUE TITLE
standardizing getter output

### ISSUE THREAD

**Issue by pfraze** [ssbc/secure-scuttlebutt#76]
in phoenix code, i've started to standardize the message objects in the `{key:, value:}` form, for two reasons: 

 1. i can modify that wrapper object without modifying the content of the message, so i can stick on new data (eg `msg.wasRead = true`)
 2. it gives me access to the msg's key

problem is that the getters are inconsistent on the output format and sometimes won't let you get it in this form

 - `createFeedStream` cant get it with keys
 - `createHistoryStream` cant get it with keys
 - `createLogStream` can only get it with keys
 - `messagesByType` respects `keys` opt
 - `messagesLinkedToMessage` cant get it with keys
 - all other link-based getters use their own format

so i'm thinking we should update the first 3 of those to respect the `keys` opt, and then update `messagesLinkedToMessage` to work like the other link-based getters

that sound good?

**Comment by pfraze** [comment]
there's a similar problem with `add`, but with a different cause

muxrpc only supports callbacks with `(err, value)` and `add` does `(err, value, key)` so the key doesnt get sent over the wire. that's a problem for some of my code right now (i need the key)

for `add` i propose we either
 - change the cb to `(err, {key:, value:})` - my preference, but possibly more work
 - change muxrpc to support multiple args in the callback

**Comment by dominictarr** [comment]
This is a good idea.
I'd prefer add to cb `{key, value}`. there might be one or two plugins that use this,
but we can change them.

**Comment by pfraze** [comment]
ok, i'll make the changes in this branch

**Comment by pfraze** [comment]
> and then update `messagesLinkedToMessage` to work like the other link-based getters

looking more deeply, it makes sense that `messagesLinkedToMessage` is different than the other link-based getters. i updated it to have a `keys:` opt instead

**Comment by pfraze** [comment]
done
