### ISSUE TITLE
normalize timestamps to UTC-0 ?

### ISSUE THREAD

**Issue by pfraze** [ssbc/secure-scuttlebutt#80]
i dont want to put timezones on the timestamps because that's location-specific info we dont need to emit. however, without correcting for timezones, posts will appear to come from the future

timestamps arent trustworthy so it's not a huge deal, but the phoenix ui uses them to order the feed (at least for now). would it be better if we normalized all timestamps on the messages to UTC-0? other machines could then convert to their local timezone

**Comment by dominictarr** [comment]
yes. it should already be like this, because if you do `+new Date()` or `Date.now()` you'll get a utc timestamp.

**Comment by pfraze** [comment]
oh really? i was not aware of that, very handy

then i'd assume `new Date(Date.now())` also does the conversion back into your local timezone?

**Comment by jbenet** [comment]
i find it best not to let parsers assume things, do add the zero-timezone `Z` to your timestamp just to make it clear it's UTC. (and :+1: on going UTC-only. wish humans did that already)

**Comment by dominictarr** [comment]
@pfraze it's actually quite difficult to get a timestamp relative to your timezone in js `(Date.now() + new Date().getTimezoneOffset() * 60)` so unless you really wanted to, and why would you? you have utc timestamps.

@jbenet UTC is good enough for now, I hate to think what we'll do once we get to space, earth time and moon time will be simple enough (each behind the other by 0.65 seconds) but then mars and venus time will slowly get closer to earth time then further away again. I think the solution is every one quits their jobs, sleeps in if they want and doesn't worry too much about what time it is.

**Comment by jtremback** [comment]
Shouldn't this be handled purely by the UI?

**Comment by dominictarr** [comment]
closing this issue, since timestamps are already utc.
