### ISSUE TITLE
cloning feeds, for compaction and other usecases

### ISSUE THREAD

**Issue by pfrazee** [ssbc/secure-scuttlebutt#83]
the distributed systems meetup had a discussion yesterday about compaction in eventually-consistent systems. it was pointed out that an operations log can be compacted by creating a new log with a new history that uses the fewest ops necessary to reconstruct the old state.

for instance, a log such as:

```
x = 5
x = 7
y = 2
x = 10
y = 3
```

could be compacted into

```
x = 10
y = 3
```

this prunes old operations which no longer have a visible effect. peers which receive the new log will (must) come to the correct state no matter when they switch from the old log.

an ssb feed should be cloneable with a similar process
1. create a new keypair
2. link to the old keypair
3. compact and copy the old feed into the new one

the compactor would scan the old feed and construct a cached state, then write the necessary ops to recreate it in the new feed. other users would have to accept the new feed if it's meant to replace the old. this may require auditing to make sure the compaction process didnt alter history.

this could be useful for compacting a feed when it grows too large, or for replacing a feed with compromised keys

**Comment by jtremback** [comment]
What are the criteria necessary to allow compaction on a feed? Clearly, a feed of status messages cannot be compacted in any meaningful way (Or if it can, it would be "lossy" compaction). Does this only apply to feeds that are keeping track of a number or boolean?

**Comment by dominictarr** [comment]
With the current design it would not be possible to verify an incomplete feed, but if we used merkle trees you could prune messages and still verify. We have been discussing merkle tree logs for a while, but we have lots of other stuff to do, so this should probably wait until v2.

**Comment by dominictarr** [comment]
And as @jtremback mentions, the prunability of a message is heavily dependant on it's application level meaning, so this is a messy problem.
