### ISSUE TITLE
feed reductions

### ISSUE THREAD

**Issue by krl** [ssbc/secure-scuttlebutt#84]
# Feed reductions

I have been thinking a bit on some concepts regarding crdts, and one way to look at it that seems to have interesting properties fall out of it is reductions.

Say you have a feed containing messages with changes to a wiki page, and you want to access the latest, or any other past state efficiently. You keep a local cache of the latest state, which you reduce over the new incoming changes. Every N messages, you create a snapshot of the reduction state, save, and optionally publish it.

As you publish the state to your peers that are following, they see that it's the same result that they got from the same reduction, and sign this snapshot. If the snapshot differs by manupilation or some bug, this will be instantly obvious.

Reductions can be over one or multiple feeds, and you can also take a snapshot, say of a wiki page that 5 feeds contributed to, and reduce in another feed, that other people might not recognize, on top of it.

This should give good security guarantees, and allows client to sync in to the latest state without recomputing all of the history.

**Comment by krl** [comment]
So, for scuttleweb, and one user publishing html files for example, it would make sense to first publish a file, and then progressivly publish diffs to this file. (or even have the first entry be a diff on the empty string)

For multi-user editable content, we would need CRDTs

**Comment by dominictarr** [comment]
@krl yeah this sounds good. the snapshots should probably point to the exact messages which it is up to sync with. that way another peer can verify their result.

Can you give a few simple examples of feed reductions that you think might be useful?

**Comment by krl** [comment]
## chess

the feed in this case would be the moves, and the reduction would be the positions of the pieces on the board.

the reduction function must be well defined, and should throw exceptions on invalid operations, for example moving a piece incorrectly.

and i think this maps interestingly on how to implement CRDTs.

## cryptocurrency

in this case the feed would be transactions and mintings, exeptions would be invalid transactions, and the state would be the balances of all known accounts.

**Comment by krl** [comment]
So, on reductions and snapshots, a feed could do its own reductions, and as part of the message provide the hash of the computed value. As each node caches its latest snapshot, it will simply update the cached version and compare it to the 'official' reduction.

**Comment by dominictarr** [comment]
chess is pretty simple, it's just a state that is the result of a fixed series of moves by two players.
so that we don't have to implement all the logic for chess, we can just make naughts-and-crosses...

Chess is particularily simple, because there is a total order for all the moves.
I'm guessing that every move should reference the previous move, and the reduced state.

A currency is a game that involves many players... I think we need a simpler example than this, because ssb doesn't have a global total order, so there are many questions that "crypto currency" raises, generally around an expectation of consistency.

**Comment by dominictarr** [comment]
Oh this also relates to what @pfraze did with https://github.com/pfraze/eco (that code is out of date now)
but we basically talking about ways to make it easy to construct new types.

Hmm, also, if multiple authors may contribute to a state, then is there a well defined order between them?
sometimes we probably want that... sometimes it doesn't matter.

**Comment by pfraze** [comment]
snapshots could also be served over RPC or HTTP instead of published on the feeds

**Comment by dominictarr** [comment]
yes, although in that case, we'd want to have some way to be able to verify the snapshot,
which is not really so simple... but would be very very awesome...
