### ISSUE TITLE
dead-feed quarantines

### ISSUE THREAD

**Issue by pfrazee** [ssbc/secure-scuttlebutt#89]
Feeds can become invalid for a couple of reasons -- a message that's too large, or a non-monotonic timestamp, for instance.

We need a way for UIs (phoenix) to become aware of and alert users about this, and we need the replication system to stop requesting the feed. At present, each replication attempt will send the dead feed's bad message along and any messages since, which is a waste of processing and bandwidth.

**Comment by dominictarr** [comment]
we also need a way to construct a proof that a feed is dead, i.e. because the key was compromised and someone posted a message that looked old.

**Comment by dominictarr** [comment]
that should then be sent to any peer that requests the feed...

**Comment by pfraze** [comment]
ohhhh that's a great idea

**Comment by dominictarr** [comment]
the simplest way to do this is just to show that two messages with the same sequence number and signature exist.
