### ISSUE TITLE
LMDB vs LevelDB

### ISSUE THREAD

**Issue by pfraze** [ssbc/secure-scuttlebutt#91]
[LMDB](http://symas.com/mdb/) is an alternative to LevelDB which stands out to me specifically due to [their claimed performance gains in read/writes of large values](http://symas.com/mdb/microbench/#sec4). Since SSB frequently works with JSON objects in the 100b-1kb range, we may find the performance difference to be important. LMDB also supports multi-thread concurrency with a global write-lock, which may be able to provide throughput gains if used correctly. The LMDB node binding seems to be in decent shape (notable bugs, https://github.com/Venemo/node-lmdb/issues/25 and https://github.com/Venemo/node-lmdb/issues/31).

Comparatively, LevelDB has more active use in the node community, and seems therefore like a more well-tested option. I recommend building a fork of SSB which uses LMDB so that we can compare their respective performance and investigate stability & portability.

**Comment by dominictarr** [comment]
@pfraze since we have leveldown shaped bindings for lmdb https://www.npmjs.com/package/lmdb
we actually just drop it into the current ssb... the "fork" would only be a few lines different... what we'd need though, is a benchmark suite.

**Comment by pfraze** [comment]
ah, handy
