### ISSUE TITLE
implementing higher level datastructures

### ISSUE THREAD

**Issue by dominictarr** [ssbc/secure-scuttlebutt#92]
impressions while implementing a higher level ssb structure for bittodo - a cryptographically secure decentralized todo list app.
1. init message + updates. I made the updates all point back to the head object with a link name the same as the type. (standardize this?)
2. Updates link to the message(s) which are the head of the structure. I think will be important to know the causal relations in the data. Another user may be looking at a slightly different version of the data to you.
3. I just made a thing where the json objects merge. (later keys overwrite earlier keys) to delete you'd just set that key to null. This will be easy except for arrays. we might need a way to remove links? Or use a sort key with [between](https://github.com/dominictarr/between) and treat every array as a set.
4. All the updates to a message are passed to a reduce function. This could be anything really. It should just be a function that takes the init + updates. This needs to do validation, etc, you might want to do merges etc. maybe this could be a collection of functions, `validate` `authorize` etc `merge` etc?
   I think we'll possibly end up storing the output of this function?
   - storing it would make sense for cases when individual objects are to be retrived... like a todo list.
   - rebuilding it would make more sense when it gets larger and larger like for discussion threading.

**Comment by dominictarr** [comment]
or maybe you could deal with the distinction between the expanding thread / updated object by aggregating and indexing a summary... which could be easy to query and mutable...
So a discussion thread could map to a small object which contained the number of replies, and time of last reply... which could be queried for notifications. but then the discussion app would pull all the messages again, and render them as a large object.

**Comment by pfraze** [comment]
I've identified the same patterns in my own projects. Lets keep adding any others we find to this thread.

I think 1 and 2 should be standard, at least as conventions.
Let's keep experimenting with 3 and 4 and try building some libraries.

**Comment by dominictarr** [comment]
:+1:

**Comment by dominictarr** [comment]
Am thinking maybe that instead of having pointers back to the initial message, a document could just have a uuid. This would be slightly easier to manage from the database, because we'd just pull all the messages with that uuid, instead of doing one query then another. On the other hand, sometimes there is really important stuff in the first message, and requiring other messages to point at it ensures there is no ambiguity about which message was first.

**Comment by dominictarr** [comment]
hmm, but then there are other cases where you don't need an initial message. say you want to star something - you don't actually need to know who got their first, just what they are staring...

**Comment by pfraze** [comment]
for indexing, you might do that via ext links, something like `{ ext: '231...ac4.uuid', rel: 'stars' }`
