### ISSUE TITLE
Messages missing from messagesByType

### ISSUE THREAD

**Issue by pfraze** [ssbc/secure-scuttlebutt#97]
**pfraze**
hmm, Im getting some unnerving behavior where `messagesByType({ type: 'init' })` isnt giving me all the init messages. Most notably, the init to my feed

**pfraze**
I changed to another feed by swapping out ~/.ssb/private, behavior remains, my main feed's init msg isnt present

**pfraze**
but the message does exist. How might my index have gotten corrupted?

**pfraze**
hmm, that's one of the indexes that gets rebuilt on version changes now (the 'idx' sublevel). I'll make an issue and look into it, maybe the rebuild botched somehow

**Comment by pfraze** [comment]
I examined a dump of my index and did find my init message in it. Therefore the index appears to be in good shape.

My init message was the first in the index, which suggests it could be a problem with how the read-stream's range is defined -- using lt/gt, for instance, when it should be lte/gte. Investigating...

**Comment by pfraze** [comment]
Turns out this was a bug in downstream code. Nothing to worry about!

**Comment by dominictarr** [comment]
for posterity, what was the bug?

**Comment by pfraze** [comment]
Incorrect format of the lt/gt params. Those params vary between functions. For `createFeedStream`, they can be `[ts, author]` iirc, while for `messagesByType` that form doesnt work, but simply `ts` does.

**Comment by dominictarr** [comment]
got it, cool.
