### ISSUE TITLE
move feed.js into another module?

### ISSUE THREAD

**Issue by dominictarr** [ssbc/secure-scuttlebutt#98]
ssb-client now depends on feed, and scuttlebot uses it from secure-scuttlebutt, but in the wrong way.
These are both probably signs that it should be moved. Also, that means we would not have to pass keys into ssb-client

https://github.com/ssbc/ssb-client/issues/2

the feed module should not take the defaults argument though... maybe we should just move feed into ssb-keys? then all the crypto is in one place!

**Comment by pfraze** [comment]
makes sense to put it in `ssb-keys`

**Comment by pfraze** [comment]
this has been done https://github.com/ssbc/ssb-feed
