### ISSUE TITLE
Improving on link-index stream functions

### ISSUE THREAD

**Issue by pfraze** [ssbc/secure-scuttlebutt#99]
This applies to the following functions:
 - `messagesLinkedToMessage`
 - `messagesLinkedToFeed`
 - `feedsLinkedToFeed`
 - `messagesLinkedFromFeed`
 - `feedsLinkedFromFeed`
 - `feedsLinkedToExternal`
 - `externalsLinkedFromFeed`

In each of these, you can specify two parameters: `(id, rel)`. The first param meaning varies between function. For instance, in `messagesLinkedToFeed`, the first param is the target feed. In `messagesLinkedFromFeed`, the first param is the origin feed. 

Ok, so I have a case now where I want to get all `rel: contact` messages published by one feed about another. So this looks like:

```js
pull(ssb.feedsLinkedToFeed(targetUser, 'contact'), pull.mapAsync(function (entry, cb) {
  if (entry.source == sourceUser)
    ssb.get(entry.message, cb)
  else
    cb()
}, ...)
```

My natural inclination is that, since the index does actually encode the information, there should be a third parameter to do do `sourceUser` filtering for me:

```js
pull(ssb.feedsLinkedToFeed(targetUser, 'contact', sourceUser), pull.mapAsync(function (entry, cb) {
  ssb.get(entry.message, cb)
}, ...)
```

Which makes me wonder if we shouldn't just generalize the functions, so that rather than having a to/from variation, we have one version for each link type (msg, feed, ext) that takes 3 params and filters based on which are given:

```js
ssb.feedsLinked(sourceUser, 'fooRel', targetUser) // from given source to give target
ssb.feedsLinked(sourceUser, 'fooRel', null) // from given source to any
ssb.feedsLinked(null, 'fooRel', targetUser) // from any to given target
ssb.messagesLinked(sourceMsg, 'fooRel', targetMsg)
ssb.messagesLinked(sourceMsg, 'fooRel')
ssb.messagesLinked(null, 'fooRel', targetMsg)
ssb.extsLinkedFromMsg(sourceMsg, 'fooRel')
ssb.extsLinkedFromFeed(sourceFeed, 'fooRel')
```

I'm also wondering why ssb doesn't get the messages for me automatically instead of making me call `get` myself

So:

 - Should we add a third param to the link-index stream funcs?
 - If so, should we generalize those functions into fewer methods?
 - Should the link-index stream funcs get the message content for us?

**Comment by dominictarr** [comment]
yes! though, i think we should be able to disable the lookup.
the multi arg calling pattern is legacy. the default style should be an object
`{from: id, rel: rel, to: id2, lookup: boolean}`

**Comment by pfraze** [comment]
ok, I like that

**Comment by pfraze** [comment]
**domanic**
what if syntax for links streams is {from: {msg:link}, to: {feed:link}, rel: <rel>}

**domanic**
then there can just be one function.

**domanic**
or maybe it should be source, dest as that is what the response is

**pfraze**
I'm cool with that

**Comment by dominictarr** [comment]
this was closed by https://github.com/ssbc/secure-scuttlebutt/pull/120
